### PR TITLE
Moved from tempfile to stdout

### PR DESCRIPTION
**Pull request by fean**
~~I re-wrote a part of the code to support stdout instead of writing to a tempfile and reading that file into memory.~~ It didn't work, which explains the approach used in this library. I also added support for the async pattern, this way the end-user can easily choose between synchronous or asynchronous implementation. And added some comments so that it's easier for users to implement.

And I fixed issue #13 as well with this update.

Also a note, because of the support of stdout for data writing, all console output has been moved to stderr.

### CODE REVIEW

**Comment by mstijak** [comment]
Thanks. I'm a little busy right now, so I'll try to review it and merge before the end of the week.

**Comment by fean** [comment]
Take your time, I have to patch out a problem as well.

**Comment by fean** [comment]
So, I think it's ready for review now. Take your time, no one is in a hurry around Christmas ;)

**Comment by fean** [comment]
Well, I thought I could move everything into one commit by deleting and re-forking. Well, that didn't work out... The commit that would've fixed the legacy was partly undone because I work in several projects. Sorry for the mess.

**Comment by mstijak** [comment]
I reverted this as it hanged when running tests. 
Writing to a file does not use application's memory so I think that it's better to leave this as is.

**Comment by fean** [comment]
Well, this is based upon the newest version of wkhtmltopdf. 
As I stated they switched from a normal stderr for errors and stdout for console output. To stdout for data output and all console output errors or not will go through stderr. That's why the current version produced #13 when I ran it with wkhtmltopdf 0.12.2.1.

Furthermore it has been updated to .net 4.5 and the support for the async pattern has been added and I made some efficiency changes. The code in my pull request runs in our environment like a charm. I was also thinking about adding batch capabilities.

**Pull request merged**
